# Generated by Django 3.1.5 on 2021-01-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lecturer',
            field=models.TextField(max_length=50000),
        ),
    ]
