# Generated by Django 3.1.5 on 2021-01-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_auto_20210110_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lecturer',
            field=models.TextField(),
        ),
    ]
