# Generated by Django 3.1.5 on 2021-01-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_auto_20210110_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='lecturer',
        ),
    ]
