# Generated by Django 3.1.5 on 2021-01-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_remove_lessons_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='lecturer',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
