# Generated by Django 3.1.5 on 2021-01-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_lessons_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lecturer',
            field=models.CharField(max_length=150),
        ),
    ]
