# Generated by Django 3.1.5 on 2021-01-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_auto_20210110_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lessons',
        ),
    ]
