# Generated by Django 3.1.5 on 2021-01-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0015_auto_20210110_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='lecturer',
            new_name='lecturer1',
        ),
        migrations.AddField(
            model_name='lessons',
            name='lecturer2',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
