# Generated by Django 3.1.5 on 2021-01-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0016_auto_20210110_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('1', 'c'), ('2', 'java'), ('3', 'python'), ('4', 'c++'), ('5', 'javascript'), ('6', 'php'), ('7', 'html'), ('8', 'css'), ('9', 'c#'), ('10', 'go'), ('11', 'Swift'), ('12', 'Dart'), ('13', 'Kotlin'), ('14', 'Ruby'), ('15', 'Kotlin ')], default='text', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessons',
            name='type',
            field=models.CharField(choices=[('1', 'c'), ('2', 'java'), ('3', 'python'), ('4', 'c++'), ('5', 'javascript'), ('6', 'php'), ('7', 'html'), ('8', 'css'), ('9', 'c#'), ('10', 'go'), ('11', 'Swift'), ('12', 'Dart'), ('13', 'Kotlin'), ('14', 'Ruby'), ('15', 'Kotlin ')], default='text', max_length=50),
            preserve_default=False,
        ),
    ]
